README.md, platform/build-scripts/src/org/jetbrains/intellij/build/SherlockProperties.kt
=> Update the README to include project's details and build instructions. 

.github/workflows/build.yml, .github/workflows/release.yml
Reverts android-graphics/sherlock-platform#40
=> Revert "Fix the file paths to the upload artifacts"

.github/workflows/build.yml, .github/workflows/release.yml
Some action versions have been deprecated. This change updates them as well as some others with their latest releases.
=> Updated versions of actions in the workflows.

README.md
=> Document MacOS "corrupted app" workaround

sherlock-platform/customization/src/com/google/sherlock/newProject/SherlockEmptyProjectGenerator.java
=> Revert project directory validation check

platform/build-scripts/src/org/jetbrains/intellij/build/SherlockProperties.kt
=> Update the distributable's name to Sherlock from Sherlock Platform

README.md
=> Update README.md to include release instructions.

.github/workflows/release.yml
Forced the release workflow to only allow creation of prereleases and fixed the file names to upload.
=> Allow creation of only prereleases. 

.github/scripts/get_version.py, .github/workflows/release.yml
Change the format for release tags and names from `VERSION=v{major}.{minor}.{patch}` to `v{major}.{minor}.{patch}`
=> Fix the release tag name.

platform/platform-resources/src/idea/LangActions.xml
=> Remove run and build menu and pop-up item

sherlock-platform/customization/resources/META-INF/SherlockPlatformCustomization.xml, sherlock-platform/customization/src/com/google/sherlock/newCapture/NewCaptureAction.kt
**Before:**
**After:**
_On clicking:_
Fixes #91
=> Introduce new capture action and button

platform/platform-resources/src/META-INF/LangExtensions.xml
Before:
After: 
Fixes #119 
Tests: Manual
=> Remove bookmarks from tool windows > bookmarks

platform/platform-resources/src/idea/LangActions.xml
Before:
After:
Fixes #122 
Test: Manual
=> Remove editor tab > bookmark

platform/platform-resources/src/idea/LangActions.xml
Before:
After:
Fixes #124 
Tests: Manual
=> Remove bookmarks from  project view pop-up > bookmark

platform/platform-resources/src/idea/LangActions.xml
Before:
After:
Fixes #126 
Test: Manual
=> Remove edit menu > bookmarks

platform/platform-resources/src/idea/PlatformActions.xml
=> Remove Tools Menu  > Services

sherlock-branding/resources/idea/SherlockPlatformApplicationInfo.xml
Required by: https://github.com/android-graphics/sherlock/issues/823
=> Fix script field in ApplicationInfo

platform/platform-api/resources/messages/IdeBundle.properties, platform/platform-impl/src/com/intellij/openapi/fileEditor/impl/EditorEmptyTextPainter.java
=> Updated the empty project helper text

sherlock-branding/resources/idea/SherlockPlatformApplicationInfo.xml
To prepare for a release that contains the new strings after #145.
=> Update version to 1.0.4

platform/platform-impl/src/com/intellij/ide/actions/OpenFileAction.kt
Related to https://github.com/android-graphics/sherlock/issues/991
Taken from: https://github.com/JetBrains/intellij-community/commit/1c340ca3746573c2d85c5d6a3904657a98e33400
=> Run associateFileType in EDT
