android-graphics/sherlock-platform

build/src/SherlockPlatformBuild.kt, build_sherlock_platform.sh, community-resources/resources/META-INF/SherlockPlatformPlugin.xml, community-resources/resources/idea/SherlockPlatformApplicationInfo.xml
Scripts that build a basic IntelliJ Platform version for Sherlock.
Steps to build: 
`./build_sherlock_platform.sh`
Steps to run:
1. `cd out/sherlock-platform/artifacts`
2.  Extract based on the OS
3. `cd sherlock-platform-242.21829/Sherlock\ Platform-2024.2.1/bin`
4. Run `sherlock-platform`
=> Sherlock's Infrastructure using IntelliJ Platform

build/src/SherlockPlatformBuild.kt, community-resources/resources/META-INF/SherlockPlatformPlugin.xml, platform/build-scripts/src/org/jetbrains/intellij/build/SherlockProperties.kt
This PR is based on #4 and should be merged only after it gets merged.
1. Created a dedicated Properties class for Sherlock that will eventually be used to configure the Sherlock distribution by specifying bundled plugins, branding etc. 
2.  Added Copyright to existing files. 
This doesn't change the functionality of the code.
=> Configured building of plugins through a dedicated Properties class.

community-resources/resources/idea/SherlockPlatformApplicationInfo.xml
Platform Type is a code that determines which IDE the platform represents (e.g., IDEA, Android Studio, PyCharm, etc).  The code 'MP' is not recognized by the IntelliJ Platform Gradle Plugin, so it gives errors when building the plugin against our custom platform. 
The code for IntelliJ IDEA is `IC`, so let's use that one.
=> Use IC as the platform type code

.idea/modules.xml, .idea/runConfigurations/Sherlock.xml, community-resources/resources/idea/SherlockPlatformApplicationInfo.xml, getPlugins.sh, intellij.idea.community.main.sherlock.iml
This change:
1. Adds an `.iml` file that represents the Sherlock platform. The `.iml` contains the absolute minimum for the Sherlock platform. Its contents should be kept in sync (or mostly similar) with the list of modules used in the `build_sherlock_platform.sh` script. Currently, it has 2 extra modules that were needed to avoid runtime exceptions.
2. Adds a run configuration that is identical to the `IDEA` run configuration except that (1) it uses the Sherlock `.iml` file for the classpath, (2) uses SherlockPlatform as the platorm prefix.
3. Updates `getPlugins.sh` to download the android repo at the correct tag automatically.
Using this change, one can:
1. Clone the `android-graphics/intellij-community` repo
2. Run `./getPlugins.sh --shallow`
3. Open the project in IntelliJ IDEA
4. …
=> Build and run Sherlock from inside IntelliJ IDEA

sherlock-branding/com.google.sherlock.branding.iml, sherlock-branding/resources/META-INF/SherlockPlatformPlugin.xml
...that was needed to include it. Also removes the redundant dependency
to the 'tips' library/jar.
This PR depends on PR #9
=> Remove JavaIdePlugin.xml include, and dependency

build_sherlock_platform.sh
On MacOS, we only need to support arm64. No need to build the x64 version.
=> Don't build for mac-x64 platform

.github/workflows/build.yml, platform/build-scripts/src/org/jetbrains/intellij/build/SherlockProperties.kt
This change adds a GitHub Actions workflow to automate the build process for the Sherlock Platform (Fixes #13)  
1. Automatically builds the Sherlock Platform whenever changes are pushed to the `idea/242.21829.142` branch or a pull request is created. 
2. The workflow sets up JDK 17 and configures the JAVA_HOME environment variable
3. Builds the platform using the `build_sherlock_platform.sh` script and generates artifact for Linux, Mac and Windows. (Have also modified ` SherlockProperties.kt` to update the name of the artifact generated. )
4. The generated artifact - `sherlock-platform` as well as `sherlock-platform-sources`  are automatically uploaded as a downloadable artifact in the workflow run,
=> Setup GitHub actions to build IntelliJ Platform.

.github/workflows/build.yml
The first step in the platform build is to download the Maven artifacts required by the build. This takes 3-4 minutes on the GitHub runners, and it's about 700-800MB in size. Using a GitHub cache that's indexed by the build.txt contents, we can reduce this down to ~10 seconds.
=> Cache maven artifacts used by IntelliJ build

.github/workflows/build.yml, .github/workflows/release.yml
This change fixes #34 - 
A new release workflow has been setup to run on every push on release tags to publish platform prebuilts for all three OS.
=> Release sherlock platform as a prebuilt

.github/workflows/build.yml
Which seems to be safer than `pull_request_target`
=> Trigger workflows using pull_request

.github/workflows/build.yml
Previous cache version in actions is deprecated as per - https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
=> Updated cache version

.github/workflows/release.yml
The previous event of `push` wasn't triggering when releases were created manually using the Github UI. This should trigger it wheever a new release is created, edited, prereleased etc.
=> Fix triggering of release.yml on releases.

.github/workflows/release.yml
it seems like it was an issue with the permissions of GITHUB_TOKEN. See "Set up job" in workflow logs to see the access.
=> Granting permissions to GITHUB_TOKEN for release workflow

.github/workflows/release.yml
The current workflow was not able to detect the downloaded artifacts because according to the github docs- 
> If the name input parameter is not provided, all artifacts will be downloaded. To differentiate between downloaded artifacts, a directory denoted by the artifacts name will be created for each individual artifact.
This change (finally!) fixes the detection of those files now. You can refer the [run](https://github.com/sonakshisaxena1/sherlock-platform/actions/runs/12779887287) on my repo that was able to successfully find and release the artifact.
=> Fixed the file detection for release workflow

sherlock-branding/resources/idea/SherlockPlatformApplicationInfo.xml
This is used as the name of the product in the main IDE UI, so it should be 'Sherlock' instead of 'Sherlock Platform'.
=> Drop 'Platform' from the name of the product

platform/build-scripts/src/org/jetbrains/intellij/build/SherlockProperties.kt, platform/build-scripts/src/org/jetbrains/intellij/build/impl/DistributionJARsBuilder.kt
This change does the following:
- Code change in the Intellij platform code to enable version change after the distributable has been generated. Fixes https://github.com/android-graphics/sherlock-platform/issues/65
- Removed a #TODO from SherlockProperties.kt as it unnecessary and a trivial change. 
- Reformatted `SherlockProperties.kt` file after the above change to be consistent with our coding style.
Tests: Manually confirmed modification of version after including this patch.
Note to the reviewer: This is similar to a change made in Studio in '23 - [ag/25533406](https://ag.corp.google.com/25533406)
=> Enable version change after generating a distributable.

.github/workflows/release.yml
When we create a release, it was starting the same workflow multiple times due to [prereleased, created, published] events all triggering simultaneously:
https://screenshot.googleplex.com/3PGL5usPimTTTEw
=> Run workflows only on `created` events

.github/workflows/release.yml
[Release for v1.0.0](https://github.com/android-graphics/sherlock-platform/actions/runs/14066409068) failed as the path in `release.yml `is relative to the workflow but the workflow expects the path relative to the root.
=> Fix release.yml xml path

platform/platform-resources/src/idea/LangActions.xml
=> Remove run, debug and run configuration widget

platform/platform-impl/src/com/intellij/ide/ui/AppearanceConfigurable.kt, platform/platform-impl/src/com/intellij/openapi/wm/impl/welcomeScreen/CustomizeTabFactory.kt
**Welcome > Customize**
_Before:_
_After:_
**Settings > Appearance:**
_Before_
_After_
Fixes #100
=> Remove accessibility support from welcome page

platform/platform-resources/src/idea/PlatformActions.xml
This got missed when we were removing "Run/Debug/Build" etc from #89 #90 
Before: 
After: 
Fixes #103
=> Remove run from settings drop-down

platform/platform-impl/src/com/intellij/openapi/wm/impl/welcomeScreen/CustomizeTabFactory.kt
Sherlock doesn't support dark theme or any other themes so we are making light theme as default. This PR removes the option to change theme on the welcome page. It will be followed by PR #110  that sets "light theme" as default.
Before: 
After:
Fixes #106
=> Removes theme/appearance option from Welcome > Customize page

platform/platform-impl/src/com/intellij/ide/ui/laf/LafManagerImpl.kt
=> Makes "light" theme as default theme for sherlock

platform/platform-impl/src/com/intellij/ide/ui/AppearanceConfigurable.kt
=> Remove theme and colors from Settings Dialog > Appearance

platform/platform-resources/src/idea/PlatformActions.xml
=> Removes "Theme..." from settings drop-down under main toolbar

platform/platform-resources/src/idea/PlatformActions.xml
=> Remove theme and color scheme from quick search

platform/platform-resources/src/META-INF/LangExtensions.xml
Before:
After:
Fixes #132 
Tests: Manual
=> Remove settings > editor > todo

platform/platform-api/resources/messages/IdeBundle.properties
Context: https://github.com/android-graphics/sherlock/issues/965
After this change:
=> Rename "capture" to "trace" in welcome page and empty project background

platform/platform-impl/src/com/intellij/ide/plugins/PluginManagerConfigurable.java
We will only have the "Installed" tab for now.
Fixes #151 
Plugins page:
When search finds no matches:
Above screenshots are taken from a manually constructed Sherlock+Platform build.
=> Disable the marketplace option in plugins page
